version: '3'

services:

  react:
    build: ./react-app
    hostname: react
    container_name: react
    ports:
      - 8080:3000
    depends_on:
      - rails
    links:
      - rails
    volumes:
      - ./react-app/book-app:/usr/src/app/book-app

  rails:
    build: ./rails-app
    hostname: rails
    container_name: rails
    ports: 
      - 3000:3000
    volumes:
      - ./rails-app/book-server:/book-server
    depends_on:
      - es01
      - es02
      - pg
    links:
      - pg
      - es01
      - es02

  pg:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - es02
    links:
      - es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/es02:/usr/share/elasticsearch/data



